//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_EMPLOYEE_WORK_EXPERIENCE_lead
    {
        public string lead_Employee_Number { get; set; }
        public string lead_Last_Name { get; set; }
        public string Department_Code { get; set; }
        public string KH_NUM { get; set; }
        public string KH_NAME { get; set; }
        public Nullable<System.DateTime> Date_From { get; set; }
        public string job_code { get; set; }
        public Nullable<System.DateTime> Date_to { get; set; }
        public int jobtype { get; set; }
        public System.DateTime ts { get; set; }
    }
}
