//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_V_SALES_SERVICERECORD
    {
        public string id { get; set; }
        public string salesName { get; set; }
        public string personStatus { get; set; }
        public string vipCustomers { get; set; }
        public string djs { get; set; }
        public string projectNames { get; set; }
        public string jobCode { get; set; }
        public string qyName { get; set; }
        public int qyRank { get; set; }
        public int allRank { get; set; }
        public decimal ddNum { get; set; }
        public decimal ddArea { get; set; }
        public decimal ddMoney { get; set; }
    }
}
