//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public System.Guid ID { get; set; }
        public string Url { get; set; }
        public string RefUrl { get; set; }
        public string RequestType { get; set; }
        public string SessionId { get; set; }
        public string Source { get; set; }
        public string Method { get; set; }
        public string Message { get; set; }
        public string StackTrace { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Ip { get; set; }
        public string HeaderContent { get; set; }
        public string UserCode { get; set; }
    }
}
