//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluationResult_New
    {
        public System.Guid ID { get; set; }
        public string Tobject { get; set; }
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public Nullable<decimal> cpfs { get; set; }
        public Nullable<int> xj { get; set; }
        public string LastFromCode { get; set; }
        public string LastFromFileName { get; set; }
        public string qyname { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<decimal> t1 { get; set; }
        public Nullable<decimal> t2 { get; set; }
        public Nullable<decimal> t3 { get; set; }
        public Nullable<decimal> t4 { get; set; }
        public Nullable<decimal> t5 { get; set; }
        public Nullable<decimal> t6 { get; set; }
        public Nullable<decimal> t7 { get; set; }
        public Nullable<decimal> t8 { get; set; }
        public Nullable<decimal> t9 { get; set; }
        public Nullable<decimal> t10 { get; set; }
        public Nullable<decimal> t11 { get; set; }
        public Nullable<decimal> t12 { get; set; }
        public Nullable<decimal> t13 { get; set; }
        public Nullable<decimal> t14 { get; set; }
        public Nullable<decimal> t15 { get; set; }
        public Nullable<decimal> t16 { get; set; }
        public Nullable<decimal> t17 { get; set; }
        public Nullable<decimal> t18 { get; set; }
        public Nullable<decimal> t19 { get; set; }
        public Nullable<decimal> t20 { get; set; }
        public Nullable<decimal> t21 { get; set; }
        public Nullable<decimal> t22 { get; set; }
        public Nullable<decimal> t23 { get; set; }
        public Nullable<decimal> t24 { get; set; }
        public Nullable<decimal> t25 { get; set; }
        public Nullable<decimal> t26 { get; set; }
        public Nullable<decimal> t27 { get; set; }
        public Nullable<decimal> t28 { get; set; }
        public Nullable<decimal> t29 { get; set; }
        public Nullable<decimal> t30 { get; set; }
        public Nullable<decimal> t31 { get; set; }
        public Nullable<decimal> t32 { get; set; }
        public Nullable<decimal> t33 { get; set; }
        public Nullable<decimal> t34 { get; set; }
        public Nullable<decimal> t35 { get; set; }
        public Nullable<decimal> t36 { get; set; }
        public Nullable<decimal> t37 { get; set; }
        public Nullable<decimal> t38 { get; set; }
        public Nullable<decimal> t39 { get; set; }
        public Nullable<decimal> t40 { get; set; }
        public Nullable<decimal> t41 { get; set; }
        public Nullable<decimal> t42 { get; set; }
        public Nullable<decimal> t43 { get; set; }
        public Nullable<decimal> t44 { get; set; }
        public Nullable<decimal> t45 { get; set; }
        public Nullable<decimal> t46 { get; set; }
        public Nullable<decimal> t47 { get; set; }
        public Nullable<decimal> t48 { get; set; }
        public Nullable<decimal> t49 { get; set; }
        public Nullable<decimal> t50 { get; set; }
    }
}
