//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluationResult
    {
        public System.Guid ID { get; set; }
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public Nullable<decimal> cpfs { get; set; }
        public Nullable<int> xj { get; set; }
        public Nullable<decimal> gznl1 { get; set; }
        public Nullable<decimal> gznl2 { get; set; }
        public Nullable<decimal> gznl3 { get; set; }
        public Nullable<decimal> gznl4 { get; set; }
        public Nullable<decimal> gzgx1 { get; set; }
        public Nullable<decimal> gzgx2 { get; set; }
        public Nullable<decimal> gzgx3 { get; set; }
        public Nullable<decimal> gzgx4 { get; set; }
        public Nullable<decimal> gzgx5 { get; set; }
        public Nullable<decimal> gzgx6 { get; set; }
        public Nullable<decimal> gzgx7 { get; set; }
        public Nullable<decimal> gzgx8 { get; set; }
        public Nullable<decimal> gzgx9 { get; set; }
        public Nullable<decimal> gzjz1 { get; set; }
        public Nullable<decimal> gzjz2 { get; set; }
        public Nullable<decimal> gzjz3 { get; set; }
        public Nullable<decimal> gzjz4 { get; set; }
        public Nullable<decimal> gzjz5 { get; set; }
        public Nullable<decimal> gzjz6 { get; set; }
        public string LastFromCode { get; set; }
        public string LastFromFileName { get; set; }
        public string qyname { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
