//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_cric_echelon_name
    {
        public int ECHELON_ID { get; set; }
        public string ECHELON_ALL_NAME { get; set; }
        public string ECHELON_SHORT_NAME { get; set; }
        public string ECHELON_VERSION { get; set; }
        public Nullable<int> ECHELON_SORT { get; set; }
    }
}
