//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_CX_Manager_Quear_Area
    {
        public string qy_name { get; set; }
        public string qy_code { get; set; }
        public Nullable<int> year { get; set; }
        public decimal q1 { get; set; }
        public decimal q2 { get; set; }
        public decimal q3 { get; set; }
        public decimal q4 { get; set; }
    }
}
