//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Course
    {
        public int ID { get; set; }
        public string Tobject { get; set; }
        public string Type { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> IsCompulsory { get; set; }
        public string beizhu { get; set; }
    }
}
