//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_DD_Manager_Month_All
    {
        public Nullable<int> year { get; set; }
        public decimal m1 { get; set; }
        public decimal m2 { get; set; }
        public decimal m3 { get; set; }
        public decimal m4 { get; set; }
        public decimal m5 { get; set; }
        public decimal m6 { get; set; }
        public decimal m7 { get; set; }
        public decimal m8 { get; set; }
        public decimal m9 { get; set; }
        public decimal m10 { get; set; }
        public decimal m11 { get; set; }
        public decimal m12 { get; set; }
    }
}
