//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Data_ProjectRaking
    {
        public Nullable<long> num { get; set; }
        public Nullable<decimal> money { get; set; }
        public string user_code { get; set; }
        public string topprojectname { get; set; }
        public Nullable<int> dd_year { get; set; }
        public Nullable<int> count { get; set; }
    }
}
