//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Data_AreaDDYearAVGForYear
    {
        public string qy_name { get; set; }
        public string type { get; set; }
        public decimal year13 { get; set; }
        public decimal year14 { get; set; }
        public decimal year15 { get; set; }
        public decimal year16 { get; set; }
        public decimal year17 { get; set; }
        public decimal year18 { get; set; }
        public Nullable<decimal> year19 { get; set; }
        public Nullable<decimal> year20 { get; set; }
    }
}
