//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_etl_employee_info
    {
        public System.Guid ID { get; set; }
        public string EMPLOYEE_NUMBER { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public string SEX { get; set; }
        public string NATIONAL_ID { get; set; }
        public string DATE_OF_BIRTH { get; set; }
        public string EJU_WORKTIME { get; set; }
        public string HS_CODE { get; set; }
        public string HS_DESC { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_DESC { get; set; }
        public string PJ_CODE { get; set; }
        public string PJ_DESC { get; set; }
        public string KH_CODE { get; set; }
        public string KH_DESC { get; set; }
        public string ORG_ID { get; set; }
        public string ORG_NAME { get; set; }
        public string JOBNAME { get; set; }
        public string JOBCLASS { get; set; }
        public string MEANING { get; set; }
        public string EMP_STATU { get; set; }
        public Nullable<int> sybid { get; set; }
        public Nullable<int> qyid { get; set; }
        public string qyname { get; set; }
        public string salary_achievement { get; set; }
    }
}
