//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Exam
    {
        public System.Guid ID { get; set; }
        public string UserCode { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> RequireType { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public string Project { get; set; }
        public Nullable<int> Result { get; set; }
        public Nullable<int> Raking { get; set; }
        public Nullable<int> JoinCount { get; set; }
        public Nullable<int> GroupRaking { get; set; }
        public Nullable<int> GroupJoinCount { get; set; }
        public string Organization { get; set; }
        public string ExamType { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> InterviewScore { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> Sequence { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> AreaRaking { get; set; }
        public Nullable<int> AreaJoinCount { get; set; }
    }
}
