//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Record
    {
        public System.Guid ID { get; set; }
        public string UserCode { get; set; }
        public string Title { get; set; }
        public Nullable<int> Sort { get; set; }
        public int Type { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Company { get; set; }
        public string Position { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> Sequence { get; set; }
        public bool IsDelete { get; set; }
        public int PartOf { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public System.DateTime Date { get; set; }
    }
}
