//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Teacher_2017
    {
        public System.Guid ID { get; set; }
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public string TeacherCode { get; set; }
        public string TeacherName { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> UpdateEndTime { get; set; }
        public Nullable<System.DateTime> ActualStartTime { get; set; }
        public Nullable<System.DateTime> ActualEndTime { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> IsEnd { get; set; }
        public Nullable<System.DateTime> InputEndDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public Nullable<System.Guid> ParID { get; set; }
        public string LastFromCode { get; set; }
        public string LastFromFileName { get; set; }
        public string qyname { get; set; }
        public string qyname2 { get; set; }
    }
}
