//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Teacher_Select
    {
        public System.Guid ID { get; set; }
        public string Type { get; set; }
        public Nullable<int> IsEnd { get; set; }
        public string UserName { get; set; }
        public string UserCode { get; set; }
        public string User_Sex { get; set; }
        public string User_ORG_NAME { get; set; }
        public string User_JOBNAME { get; set; }
        public string User_EJU_WORKTIME { get; set; }
        public string TeacherName { get; set; }
        public string TeacherCode { get; set; }
        public string Teacher_Sex { get; set; }
        public string Teacher_ORG_NAME { get; set; }
        public string Teacher_JOBNAME { get; set; }
        public string First_Job_Code { get; set; }
        public string IsLeave { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> UpdateEndTime { get; set; }
        public Nullable<System.DateTime> ActualStartTime { get; set; }
        public Nullable<System.DateTime> ActualEndTime { get; set; }
        public string teachingMonth { get; set; }
        public string teachingResult { get; set; }
        public string teachingComment { get; set; }
        public Nullable<decimal> User_avgnum { get; set; }
        public Nullable<decimal> Teacher_avgnum { get; set; }
    }
}
