//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class jianli_Employee_Information
    {
        public int id { get; set; }
        public Nullable<int> Status { get; set; }
        public string Employee_Number { get; set; }
        public string Last_Name { get; set; }
        public string Sex { get; set; }
        public string Native { get; set; }
        public string Nation { get; set; }
        public Nullable<System.DateTime> Birth_Date { get; set; }
        public string Identity_Number { get; set; }
        public Nullable<int> Politics_Status { get; set; }
        public Nullable<int> Highest_Degree { get; set; }
        public string Graduate_School { get; set; }
        public string Marital_Status { get; set; }
        public string Birth_Condition { get; set; }
        public Nullable<int> Domicile_Place { get; set; }
        public string Domicile_Address { get; set; }
        public string Domicile_Type { get; set; }
        public string Domicile_Postcode { get; set; }
        public string Now_Address { get; set; }
        public string Now_Postcode { get; set; }
        public string Telephone_Number { get; set; }
        public string Mobile_Number { get; set; }
        public string Emergency_Name { get; set; }
        public string Emergency_Relation { get; set; }
        public string Emergency_Mobile { get; set; }
        public string Housing_Fund_Number { get; set; }
        public string IsHas_OtherCompanyRelation { get; set; }
        public string OtherCompany_Name { get; set; }
        public string BreakRule_BeFired { get; set; }
        public string Fired_Reason { get; set; }
        public string IsReinstated { get; set; }
        public string Reinstated_Company { get; set; }
        public string ResidencePermit_Number { get; set; }
        public Nullable<System.DateTime> ResidencePermit_Date_Start { get; set; }
        public Nullable<System.DateTime> ResidencePermit_Date_End { get; set; }
        public string PhotoURL { get; set; }
        public string VerifierId { get; set; }
        public Nullable<System.DateTime> VerifyTime { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<int> Dept_Id { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<System.DateTime> Join_Time { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.DateTime> DeletedTime { get; set; }
        public string CreatePerson { get; set; }
        public string UpdatePerson { get; set; }
        public string DeletePerson { get; set; }
        public string VerifierReason { get; set; }
        public string CorrespondId { get; set; }
        public string BloodType { get; set; }
        public string LastPhotoURL { get; set; }
        public Nullable<int> SubmitCount { get; set; }
        public Nullable<int> PassCount { get; set; }
        public Nullable<int> RejectedCount { get; set; }
        public string OFFICE_EMAIL { get; set; }
        public Nullable<System.DateTime> CONTRACT_START_DATE { get; set; }
        public Nullable<System.DateTime> CONTRACT_END_DATE { get; set; }
    }
}
