//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class jianli_Education_Experience
    {
        public int id { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string School_Name { get; set; }
        public string Degree { get; set; }
        public string Major { get; set; }
        public string Certificate { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.DateTime> DeletedTime { get; set; }
        public string CreatePerson { get; set; }
        public string UpdatePerson { get; set; }
        public string DeletePerson { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> PERSON_ANALYSIS_ID { get; set; }
        public Nullable<int> ID_FLEX_NUM { get; set; }
    }
}
