//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class pwx_user_photo_info
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string photo_name { get; set; }
        public string photo_type { get; set; }
        public string photo_shoot_date { get; set; }
        public string photo_shoot_address { get; set; }
        public string photo_shoot_device { get; set; }
        public string photo_shoot_device_define { get; set; }
        public string photo_shoot_device_model { get; set; }
        public string photo_desc { get; set; }
        public string small_picture_url { get; set; }
        public string middle_picture_url { get; set; }
        public string big_picture_url { get; set; }
        public Nullable<int> like_num { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> status { get; set; }
    }
}
