//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class pwx_level_info
    {
        public int id { get; set; }
        public string level_type { get; set; }
        public string level_name { get; set; }
        public Nullable<decimal> min_value { get; set; }
        public Nullable<decimal> max_value { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> status { get; set; }
        public string level_code { get; set; }
    }
}
