//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class pwx_user_energy_recharge
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<decimal> pay_amount { get; set; }
        public Nullable<int> pay_status { get; set; }
        public string wx_trace_no { get; set; }
        public Nullable<System.DateTime> wx_confirm_time { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> status { get; set; }
    }
}
