//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_cux_hr_all_employee_weixin_v
    {
        public string Person_ID { get; set; }
        public string Employee_number { get; set; }
        public string Last_Name { get; set; }
        public string sex { get; set; }
        public string National_Identifier { get; set; }
        public string Person_Type_ID { get; set; }
        public string Date_Of_Birth { get; set; }
        public string Town_Of_Birth { get; set; }
        public string Office_Date { get; set; }
        public string Hukou_Address { get; set; }
        public string Hukou_Postcode { get; set; }
        public string Live_Address { get; set; }
        public string Live_Postcode { get; set; }
        public string Emergent_People { get; set; }
        public string Emergent_Phone { get; set; }
        public string Relation_Code { get; set; }
        public string Fund_Number { get; set; }
        public string Email_Address { get; set; }
        public string Unit_Code { get; set; }
        public string Join_Again { get; set; }
        public string Mobile_Code { get; set; }
        public string Family_Code { get; set; }
        public string Marital_Status { get; set; }
        public string Party_Code { get; set; }
        public string Nation_Code { get; set; }
        public string Health_Code { get; set; }
        public string Age { get; set; }
        public string People_Group_ID { get; set; }
        public string Hukou { get; set; }
        public string Phf_Area { get; set; }
        public string Person_Level { get; set; }
        public string Person_Edu { get; set; }
        public string Person_Education { get; set; }
        public string Hukou_Local { get; set; }
        public string Hukou_Type { get; set; }
        public string Work_Local { get; set; }
        public string Management_Unit { get; set; }
        public string Job_Name { get; set; }
        public string Start_Date { get; set; }
        public string Org_name { get; set; }
    }
}
