//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_etl_employee_info
    {
        public System.Guid ID { get; set; }
        public string EMPLOYEE_NUMBER { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public Nullable<int> sybid { get; set; }
        public Nullable<int> qyid { get; set; }
        public string qyname { get; set; }
        public string PJ_DESC { get; set; }
    }
}
