//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Logs_Teacher
    {
        public int id { get; set; }
        public string logsType { get; set; }
        public string logsTitle { get; set; }
        public string operName { get; set; }
        public string operPerson { get; set; }
        public string logsContent { get; set; }
        public Nullable<System.DateTime> logsDate { get; set; }
        public Nullable<int> logsLevel { get; set; }
        public string operIp { get; set; }
        public Nullable<int> exdInt { get; set; }
        public string exdStr { get; set; }
        public string exdStr1 { get; set; }
        public string exdbigStr { get; set; }
    }
}
