//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ProjectRank
    {
        public System.Guid project_id { get; set; }
        public string project_name { get; set; }
        public string user_code { get; set; }
        public Nullable<int> dd_year { get; set; }
        public Nullable<int> dd_num { get; set; }
        public Nullable<decimal> dd_area { get; set; }
        public Nullable<decimal> dd_money { get; set; }
        public Nullable<long> rn { get; set; }
        public string p_name { get; set; }
        public string p_code { get; set; }
        public string j_name { get; set; }
        public string s_name { get; set; }
        public string s_code { get; set; }
    }
}
