//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher_Select
    {
        public System.Guid ID { get; set; }
        public string Type { get; set; }
        public string UserName { get; set; }
        public string UserCode { get; set; }
        public string User_ORG_NAME { get; set; }
        public string User_JOBNAME { get; set; }
        public string User_EJU_WORKTIME { get; set; }
        public string TeacherName { get; set; }
        public string TeacherCode { get; set; }
        public string Teacher_ORG_NAME { get; set; }
        public string Teacher_JOBNAME { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> ActualStartTime { get; set; }
        public Nullable<System.DateTime> ActualEndTime { get; set; }
        public string teachingResult { get; set; }
        public Nullable<int> User_avgnum { get; set; }
        public Nullable<int> Teacher_avgnum { get; set; }
        public Nullable<int> ljcount1 { get; set; }
        public Nullable<int> ljcount2 { get; set; }
        public Nullable<int> ljcount3 { get; set; }
        public Nullable<int> ljcount4 { get; set; }
        public Nullable<int> ljcount5 { get; set; }
        public Nullable<int> ljcount6 { get; set; }
        public Nullable<int> wccount1 { get; set; }
        public Nullable<int> wccount2 { get; set; }
        public Nullable<int> wccount3 { get; set; }
        public Nullable<int> wccount4 { get; set; }
        public Nullable<int> wccount5 { get; set; }
        public Nullable<int> wccount6 { get; set; }
        public Nullable<int> td1 { get; set; }
        public Nullable<int> td2 { get; set; }
        public Nullable<int> td3 { get; set; }
        public Nullable<int> td4 { get; set; }
        public Nullable<int> td5 { get; set; }
        public Nullable<int> td6 { get; set; }
        public Nullable<int> sf1 { get; set; }
        public Nullable<int> sf2 { get; set; }
        public Nullable<int> sf3 { get; set; }
        public Nullable<int> sf4 { get; set; }
        public Nullable<int> sf5 { get; set; }
        public Nullable<int> sf6 { get; set; }
    }
}
