//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class userinfo_expand_record
    {
        public string id { get; set; }
        public string salesName { get; set; }
        public string personStatus { get; set; }
        public string vipCustomer { get; set; }
        public string djs { get; set; }
        public string projectname { get; set; }
        public string leadSalesName { get; set; }
        public string jobCode { get; set; }
        public string qyname { get; set; }
        public Nullable<int> qyrank { get; set; }
        public Nullable<int> allrank { get; set; }
        public Nullable<decimal> ddNum { get; set; }
        public Nullable<decimal> ddArea { get; set; }
        public Nullable<decimal> ddMoney { get; set; }
        public string job_short_name { get; set; }
    }
}
