//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace pingo
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_user
    {
        public int user_id { get; set; }
        public string mobile { get; set; }
        public string unionid { get; set; }
        public string openid { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string identity { get; set; }
        public string nick_name { get; set; }
        public string gender { get; set; }
        public string avatarUrl { get; set; }
        public string wx_mobile { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<sbyte> status { get; set; }
        public string work_place { get; set; }
        public string city_id { get; set; }
        public string city_name { get; set; }
        public string resource { get; set; }
        public string device_token { get; set; }
        public Nullable<int> isupdate_openid { get; set; }
    }
}
